### PR TITLE
#94 the fix for markerTags not showing up on plugin created commandBlocks

### PR DESCRIPTION
**Pull request by mrjvs**

### CODE REVIEW

**Comment by GnaspGames** [comment]
This is the implementation for #94 

Honestly I'm a little unsure whether marker entities should be created inside plugins. I can see someone setting it without realising that it will create many more than intended if they use a bang command before resetting it. 

But I'm happy to let this go and see what happens.

**Comment by mrjvs** [comment]
@GnaspGames To fix the more than intended in the delay plugin I used the setJSON function that is also suggested in a pullrequest.

**Comment by GnaspGames** [comment]
Right, I see now! Your setting the markerTag INSIDE the band command, and needed it to revert back to whatever was before the bang command was called. 

Actually that's what happens with the other JSON props like `type` and `auto`. 

https://github.com/GnaspGames/Smelt/blob/master/BangCommands/Helper.js#L21

This stops JSON properties from persisting for more than one command when used in a band command. I think I would prefer the markerTag to behave the same so that it's consistent. 

I've already started adding to this on my local version, so I'll look into it. There won't be a need for `.setJSON` then.

**Comment by mrjvs** [comment]
Great, but not a single markertag is created on plugin created command block even when the markertag is declared before the the bang command.

**Comment by GnaspGames** [comment]
Yes, that will be implemented too. I've got this. 👍

**Pull request merged**
